// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

package com.omnitracs.proto.calculator;

public interface PrimeNumberDecompositionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculator.PrimeNumberDecompositionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 prime_factor = 1;</code>
   * @return The primeFactor.
   */
  long getPrimeFactor();
}
