// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

package com.omnitracs.proto.calculator;

public interface SquareRootResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:calculator.SquareRootResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double number_root = 1;</code>
   * @return The numberRoot.
   */
  double getNumberRoot();
}
