// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blog.proto

package com.omnitracs.proto.blog;

public interface CreateBlogRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:blog.CreateBlogRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * the id shouldn't matter
   * </pre>
   *
   * <code>.blog.Blog blog = 1;</code>
   * @return Whether the blog field is set.
   */
  boolean hasBlog();
  /**
   * <pre>
   * the id shouldn't matter
   * </pre>
   *
   * <code>.blog.Blog blog = 1;</code>
   * @return The blog.
   */
  com.omnitracs.proto.blog.Blog getBlog();
  /**
   * <pre>
   * the id shouldn't matter
   * </pre>
   *
   * <code>.blog.Blog blog = 1;</code>
   */
  com.omnitracs.proto.blog.BlogOrBuilder getBlogOrBuilder();
}
