// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: blog.proto

package com.omnitracs.proto.blog;

public interface ListBlogRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:blog.ListBlogRequest)
    com.google.protobuf.MessageOrBuilder {
}
